### ISSUE TITLE
DatePicker min date not working correctly

### ISSUE THREAD

**Issue by gunwixor** [ng-matero/extensions#349] opened 2024-10-06 23:12 UTC
That's wired. When **start datetime** choosed, it's minimum date of **end datetime**, but when I selected end date, it's still in current my pc time. Minimum date doesn't work correctly. I attached my record video.

https://github.com/user-attachments/assets/b530a7ee-052d-4a47-8ee6-ce0b4abdccce

**Comment by nzbin** [comment] 2024-10-08 01:40
@JelleBruisten Do you know this issue?

**Comment by JelleBruisten** [comment] 2024-10-08 19:37
@nzbin I don't seem to experience this bug, and we use multiple min/max dates through the system.

**Comment by gunwixor** [comment] 2024-10-09 05:14
@JelleBruisten  I'm using MomentDateAdapter.

**Comment by nzbin** [comment] 2024-10-09 14:04
Can you provide an online example?

**Comment by nzbin** [comment] 2024-10-12 10:37
Duplicate of #344

**Closed by nzbin** 2024-10-12 10:37 UTC
Labels: duplicate, area: datetimepicker

**Comment by gunwixor** [comment] 2024-10-25 10:40
@nzbin  It's not completed yet.

**Comment by JelleBruisten** [comment] 2024-10-25 11:16
It's a duplicate issue it seems
